LastPageIndexing = 20110422115412
WikiTitle = ScrewTurn Wiki
MainUrl = http://www.server.com/
ContactEmail = info@server.com
SenderEmail = no-reply@server.com
ErrorsEmails = 
SmtpServer = smtp.server.com
SmtpPort = -1
SmtpUsername = admin
SmtpPassword = csw3coder
SmtpSsl = no
Theme = Default
DefaultPage = MainPage
DateTimeFormat = yyyy'/'MM'/'dd' 'HH':'mm
DefaultLanguage = tr-TR
DefaultTimezone = 0
MaxRecentChangesToDisplay = 10
RssFeedsMode = Summary
EnableDoubleClickEditing = no
EnableSectionEditing = yes
EnableSectionAnchors = yes
EnablePageToolbar = yes
EnableViewPageCode = yes
EnablePageInfoDiv = yes
DisableBreadcrumbsTrail = no
AutoGeneratePageNames = yes
ProcessSingleLineBreaks = no
UseVisualEditorAsDefault = no
KeptBackupNumber = -1
DisplayGravatars = yes
UsersCanRegister = yes
UsernameRegex = ^\w[\w\ !$@%^\.\(\)\-_]{3,25}$
PasswordRegex = ^\w[\w~!@#$%^\(\)\[\]\{\}\.,=\-_\ ]{5,25}$
AccountActivationMode = EMAIL
UsersGroup = Users
AdministratorsGroup = Administrators
AnonymousGroup = Anonymous
DisableCaptchaControl = no
DisableConcurrentEditing = no
ChangeModerationMode = None
AllowedFileTypes = jpg|jpeg|gif|png|tif|tiff|bmp|svg|htm|html|zip|rar|pdf|txt|doc|xls|ppt|docx|xlsx|pptx
FileDownloadCountFilterMode = CountAll
FileDownloadCountFilter = 
MaxFileSize = 10240
ScriptTagsAllowed = no
LoggingLevel = 3
MaxLogSize = 256
IpHostFilter = 
DisableAutomaticVersionCheck = no
DisableCache = no
CacheSize = 100
CacheCutSize = 20
EnableViewStateCompression = no
EnableHttpCompression = no
