LastPageIndexing = 20110515210713
WikiTitle = Çınar Teknoloji
MainUrl = http://www.cinarteknoloji.com/
ContactEmail = bulentkeskin@gmail.com
SenderEmail = bulentkeskin@gmail.com
ErrorsEmails = bulentkeskin@gmail.com
SmtpServer = smtp.server.com
SmtpPort = -1
SmtpUsername = admin
SmtpPassword = csw3coder
SmtpSsl = no
Theme = Default
DefaultPage = MainPage
DateTimeFormat = dd'/'MM'/'yyyy' 'HH':'mm
DefaultLanguage = en-US
DefaultTimezone = 120
MaxRecentChangesToDisplay = 10
RssFeedsMode = Summary
EnableDoubleClickEditing = no
EnableSectionEditing = no
EnableSectionAnchors = no
EnablePageToolbar = yes
EnableViewPageCode = no
EnablePageInfoDiv = no
DisableBreadcrumbsTrail = yes
AutoGeneratePageNames = yes
ProcessSingleLineBreaks = no
UseVisualEditorAsDefault = no
KeptBackupNumber = 10
DisplayGravatars = yes
UsersCanRegister = yes
UsernameRegex = ^\w[\w\ !$@%^\.\(\)\-_]{3,25}$
PasswordRegex = ^\w[\w~!@#$%^\(\)\[\]\{\}\.,=\-_\ ]{5,25}$
AccountActivationMode = EMAIL
UsersGroup = Users
AdministratorsGroup = Administrators
AnonymousGroup = Anonymous
DisableCaptchaControl = no
DisableConcurrentEditing = no
ChangeModerationMode = RequirePageEditingPermissions
AllowedFileTypes = jpg|jpeg|gif|png|tif|tiff|bmp|svg|htm|html|zip|rar|pdf|txt|doc|xls|ppt|docx|xlsx|pptx
FileDownloadCountFilterMode = CountAll
FileDownloadCountFilter = 
MaxFileSize = 10240
ScriptTagsAllowed = no
LoggingLevel = 3
MaxLogSize = 256
IpHostFilter = 
DisableAutomaticVersionCheck = no
DisableCache = no
CacheSize = 100
CacheCutSize = 20
EnableViewStateCompression = no
EnableHttpCompression = no
