//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinar.DBTools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQLResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cinar.DBTools.SQLResources", typeof(SQLResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Class {
            get {
                object obj = ResourceManager.GetObject("Class", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Interface {
            get {
                object obj = ResourceManager.GetObject("Interface", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LocalVariable {
            get {
                object obj = ResourceManager.GetObject("LocalVariable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Method {
            get {
                object obj = ResourceManager.GetObject("Method", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Property {
            get {
                object obj = ResourceManager.GetObject("Property", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///
        ///&lt;SyntaxDefinition name =&quot;SQL&quot; extensions = &quot;.sql&quot;&gt;
        ///	
        ///	&lt;Properties&gt;
        ///		&lt;Property name=&quot;LineComment&quot; value=&quot;--&quot;/&gt;
        ///	&lt;/Properties&gt;
        ///
        ///	&lt;Digits name =&quot;Digits&quot; bold =&quot;false&quot; italic =&quot;false&quot; color =&quot;DarkBlue&quot;/&gt;
        ///
        ///	&lt;RuleSets&gt;
        ///		&lt;RuleSet ignorecase = &quot;true&quot;&gt;
        ///			&lt;Delimiters&gt;=!&amp;gt;&amp;lt;+-/*%&amp;amp;|^~.}{,;][?:()&lt;/Delimiters&gt;
        ///			
        ///			&lt;Span name =&quot;LineComment&quot; bold =&quot;false&quot; italic =&quot;false&quot; color =&quot;DarkSlateGray&quot; stopateol =&quot;true&quot;&gt;
        ///				&lt;Begin&gt;-- &lt;/Begin&gt;
        ///			&lt;/Span&gt;
        ///					
        ///			&lt;Span name =&quot;B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL {
            get {
                return ResourceManager.GetString("SQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///This &quot;query by script&quot; calculates optimal data lengths for the (var)char columns.
        ///To achive this, it finds the max length of the data and compare it to the defined length.
        ///This is useful to decrease both memory &amp; disk consumption.
        ///*/
        ///$
        ///bool firstUnionSkipped = false;
        ///foreach(var t in db.Tables)
        ///	foreach(var f in t.Columns){
        ///		if(f.IsStringType()==false) continue;
        ///		if(firstUnionSkipped) echo(&quot;UNION&quot;);
        ///		firstUnionSkipped = true;
        ///		$
        ///		select &apos;$=t.Name$&apos; as table_name, &apos;$=f.Name$&apos; as column_n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQLCalculateOptimalDataLength {
            get {
                return ResourceManager.GetString("SQLCalculateOptimalDataLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELIMITER $$
        ///
        ///CREATE FUNCTION &lt;function_name&gt;()
        ///    RETURNS TYPE
        ///    BEGIN
        ///
        ///    END$$
        ///
        ///DELIMITER ;.
        /// </summary>
        internal static string SQLCreateFunctionMySQL {
            get {
                return ResourceManager.GetString("SQLCreateFunctionMySQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE FUNCTION function_name
        ///  (input_parameter_name datatype, ...)
        ///RETURNS datatype
        ///AS $$
        ///DECLARE
        ///  variable_name datatype;
        ///BEGIN
        ///  /* SQL code */
        ///END;
        ///$$ LANGUAGE plpgsql;.
        /// </summary>
        internal static string SQLCreateFunctionPostgreSQL {
            get {
                return ResourceManager.GetString("SQLCreateFunctionPostgreSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELIMITER $$
        ///
        ///CREATE PROCEDURE &lt;procedure_name&gt;()
        ///    BEGIN
        ///
        ///    END$$
        ///
        ///DELIMITER ;.
        /// </summary>
        internal static string SQLCreateSProcMySQL {
            get {
                return ResourceManager.GetString("SQLCreateSProcMySQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE FUNCTION function_name
        ///  (input_parameter_name datatype, ...)
        ///RETURNS return_type
        ///AS $$
        ///DECLARE
        ///  variable_name datatype;
        ///BEGIN
        ///  /* SQL code */
        ///END;
        ///$$ LANGUAGE plpgsql;.
        /// </summary>
        internal static string SQLCreateSProcPostgreSQL {
            get {
                return ResourceManager.GetString("SQLCreateSProcPostgreSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE nameprocedure
        ///  (input_parameter_name datatype, ... )
        ///AS
        ///  /* SQL code */
        ///GO.
        /// </summary>
        internal static string SQLCreateSProcSQLServer {
            get {
                return ResourceManager.GetString("SQLCreateSProcSQLServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELIMITER $$
        ///
        ///CREATE
        ///    TRIGGER &lt;trigger_name&gt; BEFORE/AFTER INSERT/UPDATE/DELETE
        ///    ON &lt;table_name&gt;
        ///    FOR EACH ROW BEGIN
        ///
        ///    END$$
        ///
        ///DELIMITER ;.
        /// </summary>
        internal static string SQLCreateTriggerMySQL {
            get {
                return ResourceManager.GetString("SQLCreateTriggerMySQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW &lt;view_name&gt; 
        ///    AS
        ///(SELECT * FROM ...);.
        /// </summary>
        internal static string SQLCreateViewMySQL {
            get {
                return ResourceManager.GetString("SQLCreateViewMySQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Struct {
            get {
                object obj = ResourceManager.GetObject("Struct", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap table_edit {
            get {
                object obj = ResourceManager.GetObject("table_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
